# -*- coding: utf-8 -*-
"""Activity1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sWaMk-AtCYN35YlWoJBG8vqRQrxTL6ct
"""

def intersection (list1, list2):
    intersection = []
    for i in list1:
        for j in list2:
            if i == j:
                intersection.append(i)
                break
    return intersection

A = [2, 4, 5, 6]
B = [4, 6, 7, 8]

result = intersection(A, B)
print(result)